import 'package:finanzas_lite/models/budgets/budget_view_model.dart';
import 'package:finanzas_lite/models/transactions/transactions_view_model.dart';
import 'package:flutter/widgets.dart';
import 'package:get/state_manager.dart';

class BudgetsState extends GetxController {
  final budgets = <BudgetViewModel>[
    BudgetViewModel(
      id: '1',
      color: Color(0xFFFFD466),
      name: "Comida",
      currentAmountSpent: 3430,
      limit: 5000,
      transactions: [
        TransactionViewModel(
          acountNames: ["Cuenta principal"],
          mainColor: const Color(0xFF6A66FF),
          icon: "assets/svgs/categoryIcons/comida.svg",
          amount: 120.50,
          categoriesName: ["Comida", "Restaurante"],
          date: DateTime.now().subtract(const Duration(days: 1)),
          id: '1',
          type: TransactionType.expense,
          description: 'Papubuelo se nos fue',
        ),
        TransactionViewModel(
          acountNames: ["Tarjeta crédito"],
          mainColor: const Color(0xFFE840D1),
          icon: "assets/svgs/categoryIcons/maleta.svg",
          amount: 890.20,
          categoriesName: ["Compras", "Ropa"],
          date: DateTime.now().subtract(const Duration(days: 3)),
          id: '2',
          type: TransactionType.income,
          description: 'Papubuelo se nos fue',
        ),
        TransactionViewModel(
          acountNames: ["Cuenta de ahorro"],
          mainColor: const Color(0xFF4CAF50),
          icon: "assets/svgs/categoryIcons/bicicleta.svg",
          amount: -45.00,
          categoriesName: ["Transporte"],
          date: DateTime.now().subtract(const Duration(days: 5)),
          id: '3',
          type: TransactionType.transfer,
          description: 'Papubuelo se nos fue',
        ),
        TransactionViewModel(
          acountNames: ["Cuenta principal"],
          mainColor: const Color(0xFF6A66FF),
          icon: "assets/svgs/categoryIcons/comida.svg",
          amount: 120.50,
          categoriesName: ["Comida", "Restaurante"],
          date: DateTime.now().subtract(const Duration(days: 1)),
          id: '1',
          type: TransactionType.expense,
          description: 'Papubuelo se nos fue',
        ),
        TransactionViewModel(
          acountNames: ["Tarjeta crédito"],
          mainColor: const Color(0xFFE840D1),
          icon: "assets/svgs/categoryIcons/maleta.svg",
          amount: 890.20,
          categoriesName: ["Compras", "Ropa"],
          date: DateTime.now().subtract(const Duration(days: 3)),
          id: '2',
          type: TransactionType.income,
          description: 'Papubuelo se nos fue',
        ),
        TransactionViewModel(
          acountNames: ["Cuenta de ahorro"],
          mainColor: const Color(0xFF4CAF50),
          icon: "assets/svgs/categoryIcons/bicicleta.svg",
          amount: -45.00,
          categoriesName: ["Transporte"],
          date: DateTime.now().subtract(const Duration(days: 5)),
          id: '3',
          type: TransactionType.transfer,
          description: 'Papubuelo se nos fue',
        ),
        TransactionViewModel(
          acountNames: ["Cuenta principal"],
          mainColor: const Color(0xFF6A66FF),
          icon: "assets/svgs/categoryIcons/comida.svg",
          amount: 120.50,
          categoriesName: ["Comida", "Restaurante"],
          date: DateTime.now().subtract(const Duration(days: 1)),
          id: '1',
          type: TransactionType.expense,
          description: 'Papubuelo se nos fue',
        ),
        TransactionViewModel(
          acountNames: ["Tarjeta crédito"],
          mainColor: const Color(0xFFE840D1),
          icon: "assets/svgs/categoryIcons/maleta.svg",
          amount: 890.20,
          categoriesName: ["Compras", "Ropa"],
          date: DateTime.now().subtract(const Duration(days: 3)),
          id: '2',
          type: TransactionType.income,
          description: 'Papubuelo se nos fue',
        ),
        TransactionViewModel(
          acountNames: ["Cuenta de ahorro"],
          mainColor: const Color(0xFF4CAF50),
          icon: "assets/svgs/categoryIcons/bicicleta.svg",
          amount: -45.00,
          categoriesName: ["Transporte"],
          date: DateTime.now().subtract(const Duration(days: 5)),
          id: '3',
          type: TransactionType.transfer,
          description: 'Papubuelo se nos fue',
        ),
        TransactionViewModel(
          acountNames: ["Cuenta principal"],
          mainColor: const Color(0xFF6A66FF),
          icon: "assets/svgs/categoryIcons/comida.svg",
          amount: 120.50,
          categoriesName: ["Comida", "Restaurante"],
          date: DateTime.now().subtract(const Duration(days: 1)),
          id: '1',
          type: TransactionType.expense,
          description: 'Papubuelo se nos fue',
        ),
        TransactionViewModel(
          acountNames: ["Tarjeta crédito"],
          mainColor: const Color(0xFFE840D1),
          icon: "assets/svgs/categoryIcons/maleta.svg",
          amount: 890.20,
          categoriesName: ["Compras", "Ropa"],
          date: DateTime.now().subtract(const Duration(days: 3)),
          id: '2',
          type: TransactionType.income,
          description: 'Papubuelo se nos fue',
        ),
        TransactionViewModel(
          acountNames: ["Cuenta de ahorro"],
          mainColor: const Color(0xFF4CAF50),
          icon: "assets/svgs/categoryIcons/bicicleta.svg",
          amount: -45.00,
          categoriesName: ["Transporte"],
          date: DateTime.now().subtract(const Duration(days: 5)),
          id: '3',
          type: TransactionType.transfer,
          description: 'Papubuelo se nos fue',
        ),
        TransactionViewModel(
          acountNames: ["Cuenta principal"],
          mainColor: const Color(0xFF6A66FF),
          icon: "assets/svgs/categoryIcons/comida.svg",
          amount: 120.50,
          categoriesName: ["Comida", "Restaurante"],
          date: DateTime.now().subtract(const Duration(days: 1)),
          id: '1',
          type: TransactionType.expense,
          description: 'Papubuelo se nos fue',
        ),
        TransactionViewModel(
          acountNames: ["Tarjeta crédito"],
          mainColor: const Color(0xFFE840D1),
          icon: "assets/svgs/categoryIcons/maleta.svg",
          amount: 890.20,
          categoriesName: ["Compras", "Ropa"],
          date: DateTime.now().subtract(const Duration(days: 3)),
          id: '2',
          type: TransactionType.income,
          description: 'Papubuelo se nos fue',
        ),
        TransactionViewModel(
          acountNames: ["Cuenta de ahorro"],
          mainColor: const Color(0xFF4CAF50),
          icon: "assets/svgs/categoryIcons/bicicleta.svg",
          amount: -45.00,
          categoriesName: ["Transporte"],
          date: DateTime.now().subtract(const Duration(days: 5)),
          id: '3',
          type: TransactionType.transfer,
          description: 'Papubuelo se nos fue',
        ),
      ],
    ),
    BudgetViewModel(
      id: '1',
      color: Color(0xFF66FFA3),
      name: "Transporte",
      currentAmountSpent: 4300,
      limit: 800,
      transactions: [],
    ),
    BudgetViewModel(
      id: '1',
      color: Color(0xFF3DB9FF),
      name: "Salud",
      currentAmountSpent: 3000,
      limit: 5000.25,
      transactions: [],
    ),
    BudgetViewModel(
      id: '1',
      color: Color(0xFFFFD466),
      name: "Vida Diaría DEL PEPE Y ETE SECH",
      currentAmountSpent: 2500,
      limit: 5000,
      transactions: [],
    ),
  ];

  void onGoBack(BuildContext context) {
    Navigator.of(context).pop();
  }
}
